// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {battle} from '../models';

export function GetDemoBattle():Promise<battle.Battle>;
